### ISSUE TITLE
Criar Rascunhos dos Milestones 

### ISSUE THREAD

**Issue by giclayne** [Socorro-Projetao/socorro#10]
Criar rascunhos dos milestones. 

Link da documentação 

[Definição do projeto](https://docs.google.com/document/d/1pOPrBcSiAA3NI0us8a3VZT5xz2uDA2rIdM4e_u2QLuo/edit)
[História de usuários | MER | Protótipo Inicial](https://docs.google.com/document/d/1-i16qtuT6SRj2m4C9Nv3nBQ4aFyuRS_4MnmMf7GGBt8/edit)
[Pitch](https://www.canva.com/design/DAGKmEbC6XA/sP4n-nDbR6zSqpXV_skEDA/edit)

**Comment by antoniobezerra01** [comment]
Segue a versão inicial do Milestones 

[Milestone - V1 .docx](https://github.com/user-attachments/files/16197657/Milestone.-.V1.docx)
[Milestone - V1 .pdf](https://github.com/user-attachments/files/16197658/Milestone.-.V1.pdf)

Link no driver: https://docs.google.com/document/d/1sLK28kE6wJyAq0jMCiW2YMuemoc3-ybGTcyGP_JO618/edit
