### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by giclayne** [Socorro-Projetao/socorro#67]
- [x] Login
- [x] CRUD Cliente
- [x] CRUD Profissional

TESTAR: 
- Funcionalidade
- Validação dos campos
- Tipo de input que recebe
Entre outros

**Comment by giclayne** [comment]
* Cliente
1. Máscara do campo TELEFONE
2. Obrigatoriedade de imagem
3. BUG -> Depois de cadastrar, ele mostra a home do cliente e depois a mensagem de 'CADASTRO SUCESSO'

* Profissional 
1. Máscara do campo TELEFONE
2. Validação do campo instagram (@)
3.  BUG do item 3 do cliente, NÃO OCORRE
4. Ao não preencher o campo de localização, e cadastrar, aparece a mensagem de sucesso no cadastro, mas não cadastra

**Comment by Hester910** [comment]
* Cliente

1.  BUG na atualização do cadastro: Muda pra tela do CRUD enquanto mostra a mensagem de sucesso na atualização

* Profissional

1. BUG no cadastro: da tela de confirmação ele vai sozinho para a home ao invés de aguardar a ação no botão de CONTINUAR;
2. Subir mais o conteúdo de edição dos dados;
